# stable-diffusion-api/Dockerfile
FROM python:3.9-slim

# Install git (if needed) and other dependencies
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy requirements and install them
COPY ./stable-diffusion/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the code
COPY ./stable-diffusion/api.py /app/

# Expose port 5000
EXPOSE 5003

# Run the Flask app
CMD ["python", "api.py"]